#!/usr/bin/env zsh

path_=$(realpath $1)
compdb=$2/compile_commands.json
extraargs=$3

cmd=$(python3 "$HOME/.config/nvim/make_command.py" "$compdb" "$path_")

eval "$cmd $extraargs"

# echo  "$cmd $extraargs"
